// <auto-generated />
namespace EQRSWin.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedSettingDb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedSettingDb));
        
        string IMigrationMetadata.Id
        {
            get { return "201703060422109_addedSettingDb"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
